
#include "nsISupports.idl"
#include "nsIObserver.idl"
#include "nsIDOMElement.idl"
#include "nsIXMPPClientSession.idl"

interface nsIObserver;

[scriptable, uuid(b8a71ae4-8419-4768-9255-3735126f69a9)]
interface nsIXMPPConnector: nsISupports
{
    void init(in string jid, in string password, in string host, in long port, in unsigned short security);

    boolean write(in AUTF8String data);

    void send(in nsIDOMElement element);

    boolean isConnected();

    boolean isOpen();

    void setSession(in nsIXMPPClientSession sess);

    void connect();

    void disconnect();

 	void addObserver(in nsIObserver anObserver, in string aTopic, in boolean ownsWeak);

    void removeObserver(in nsIObserver anObserver, in string aTopic);

    void notifyObservers(in nsISupports aSubject, in string aTopic, in wstring someData);
};  
