#include "nsISupports.idl"
#include "nsIDOMElement.idl"

[scriptable, uuid(8c95c531-d757-40a0-aa54-8cfbd47065ba)]
interface nsIXMPPCacheService: nsISupports
{
    nsISupports all(in string query);

    nsISupports first(in string query);

    void receive(in nsIDOMElement element);

    string toString();
};
