#include "nsISupports.idl"
#include "nsIObserver.idl"

interface nsIObserver;

[scriptable, uuid(0fa2417d-60a7-4d53-ba9a-b63cfbee96a4)]
interface nsIXMPPClientSession: nsISupports
{
    void reload();

    void open(in string hostName);

    void close();

    boolean isOpen();

    void send(in string data, in nsIObserver replyObserver);

    void receive(in string data);

 	void addObserver(in nsIObserver anObserver, in string aTopic, in boolean ownsWeak);

    void removeObserver(in nsIObserver anObserver, in string aTopic);

    void notifyObservers(in nsISupports aSubject, in string aTopic, in wstring someData);

    void setName(in string name);
    
    attribute string name;
};  
